version: 2

sources:
  - name: raw
    database: ECOMMERCE_DB
    schema: RAW
    tables:
      - name: raw_orders
      - name: raw_customers
      - name: raw_products
      - name: raw_order_items
      - name: raw_order_payments
      - name: raw_order_reviews